baseURL = "https://tom-felix-thormann.github.io/"
title = "Tom-Felix Thormann"
theme = "hugo-paper"
languageCode = "en-us"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  name = "Tom-Felix Thormann"
  github = "Tom-Felix-Thormann"
  linkedin = "tom-felix-thormann-b209a3262"
  orcid = "0009-0005-1928-6365"
  email = "tom-felix.thormann@ruhr-uni-bochum.de"
  favicon = "favicon.png"

[menu]

[[menu.main]]
name = "Publications"
url = "/publications/"
weight = 1

[[menu.main]]
name = "Talks"
url = "/talks/"
weight = 2

[[menu.main]]
name = "CV"
url = "/cv/"
weight = 3